#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#

(defpackage :ros-script.fetch-gist-build
  (:use :cl)
  (:export #:main))

(in-package :ros-script.fetch-gist-build)

(let ((root (merge-pathnames "../"
                             (make-pathname :defaults *load-truename*
                                            :name nil :type nil))))
  (push root asdf:*central-registry*))

(ql:quickload "fetch-gist")

(defun cl-user::fetch-gist-main (&rest args)
  (apply #'uiop:symbol-call '#:fetch-gist.cli '#:main args))

(defun build ()
  (let* ((root (merge-pathnames "../"
                               (make-pathname :defaults *load-truename*
                                              :name nil :type nil)))
         (source (merge-pathnames "tool/build" root))
         (script (merge-pathnames "fetch-gist-build.ros"
                                 (uiop:temporary-directory)))
         (target (merge-pathnames "bin/fetch-gist" root)))
    (ensure-directories-exist target)
    (unwind-protect
         (progn
           (when (probe-file script)
             (delete-file script))
           (uiop:run-program (list "ln" "-s" (namestring source)
                                   (namestring script)))
           (uiop:run-program (list "ros" "--entry" "cl-user::fetch-gist-main"
                                   "dump" "executable" (namestring script)
                                   "-o" (namestring target))
                             :directory root))
      (when (probe-file script)
        (delete-file script)))
    (format t "Built ~A~%" (namestring target))))

(defun test ()
  (asdf:test-system "fetch-gist"))

(defun usage (&optional (stream *standard-output*))
  (format stream "Usage: tool/build <build|test>~%")
  (format stream "~@{~A~%~}"
          "Commands:"
          "  build  Load and compile the fetch-gist system."
          "  test   Load fetch-gist and run its test suite."))

(defun main (&rest args)
  (let ((subcommand (first args)))
    (cond
      ((or (null subcommand)
           (string= subcommand "help")
           (string= subcommand "--help"))
       (usage)
       (uiop:quit 0))
      ((string= subcommand "build")
       (build)
       (uiop:quit 0))
      ((string= subcommand "test")
       (test)
       (uiop:quit 0))
      (t
       (format *error-output* "tool/build: unknown command: ~A~%"
               subcommand)
       (usage *error-output*)
       (uiop:quit 1)))))
